CREATE TABLE IF NOT EXISTS movimentacoes_pontos (
                                                    id_movimentacao INTEGER GENERATED BY DEFAULT AS IDENTITY,
                                                    cpf_cliente VARCHAR(14) NOT NULL,
    id_loc INTEGER,
    tipo VARCHAR(20) NOT NULL,
    quantidade INTEGER NOT NULL,
    data_hora TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            descricao VARCHAR(255) NOT NULL,

    CONSTRAINT pk_movimentacoes_pontos
    PRIMARY KEY (id_movimentacao),

    CONSTRAINT fk_movimentacoes_pontos_cliente
    FOREIGN KEY (cpf_cliente)
    REFERENCES clientes(cpf),

    CONSTRAINT fk_movimentacoes_pontos_locacao
    FOREIGN KEY (id_loc)
    REFERENCES locacoes(id_loc),

    CONSTRAINT uk_movimentacao_locacao_tipo
    UNIQUE (id_loc, tipo),

    CONSTRAINT ck_movimentacoes_pontos_tipo
    CHECK (tipo IN ('CREDITO', 'RESGATE')),

    CONSTRAINT ck_movimentacoes_pontos_quantidade
    CHECK (quantidade > 0)
    );

CREATE INDEX IF NOT EXISTS idx_movimentacoes_pontos_cliente
    ON movimentacoes_pontos(cpf_cliente);

CREATE INDEX IF NOT EXISTS idx_movimentacoes_pontos_data
    ON movimentacoes_pontos(data_hora);