# Configurações da Porta e Nome da Aplicação
server.port=3000
spring.application.name=RentFlow

# Conexão com o Banco de Dados (Supabase PostgreSQL)
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?stringtype=unspecified}
spring.datasource.username=${DB_USERNAME:postgres.mxfgyfxcviitbnllkatv}
spring.datasource.password=${DB_PASSWORD:DB2026_ufrpe}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA / Hibernate
# ATENÇÃO: Como o banco já existe com tabelas e ENUMs criados, não devemos usar 'update' ou 'create'
# Utilizaremos 'validate' apenas para validar se as entidades mapeiam corretamente para as tabelas existentes
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ajuste no dialeto para trabalhar corretamente com o PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Desativar cache do Thymeleaf durante desenvolvimento para as páginas recarregarem instantaneamente
spring.thymeleaf.cache=false
